DOMAIN = "tado_boost"
PLATFORMS = []
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
DEFAULT_SCAN_INTERVAL = 60
DEFAULT_BOOST_MINUTES = 15
DATA_COORDINATOR = "coordinator"
API_CLIENT = "api_client"

